# This file was generated by GoReleaser. DO NOT EDIT.
cask "dedalus" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_macos_amd64.zip"
      sha256 "113e30cd9dcdfd6ee00178c8f07a7b95d6f19a1c12bda716fb85c514688a9654"
    end
    on_arm do
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_macos_arm64.zip"
      sha256 "6cf2b80bdec5b6750ad8535659a82bcad0b2d05d4d4db846c15f736ec6b1dad8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_linux_amd64.tar.gz"
      sha256 "5d675e37b2d3f6da76339e59fc3f979c9918248c8e88576a9f8cf86159a42862"
    end
    on_arm do
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_linux_arm64.tar.gz"
      sha256 "a12d12fc6ba23265d0b59ab40443f3db77e17c2ae6f3c80549a5996b7be4e389"
    end
  end

  name "dedalus"
  desc "The official CLI for Dedalus."
  homepage "https://docs.dedaluslabs.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dedalus"
  manpage "man/man1/dedalus.1.gz"
  bash_completion "completions/dedalus.bash"
  fish_completion "completions/dedalus.fish"
  zsh_completion "completions/dedalus.zsh"

  # No zap stanza required

end
