# This file was generated by GoReleaser. DO NOT EDIT.
cask "dedalus" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "4afd89acef1fef035e99e20663f68576ec82d0d360f12adae080d89d1b739c5a"
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "f3044fc14507ea1eeec179d58a8b9ab8a082ec14bdef2627cf8042e40a23dde5"
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "48cb2795b408ff84aa8be152240488e28bcaf1468870c5459c5c6907e67c95be"
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6ab6817b104f44ea11e737eff102b26b8501c6310f32c9adc507f685408c0f7"
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dedalus"
  desc "The official CLI for Dedalus."
  homepage "https://docs.dedaluslabs.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dedalus"
  manpage "man/man1/dedalus.1.gz"
  bash_completion "completions/dedalus.bash"
  fish_completion "completions/dedalus.fish"
  zsh_completion "completions/dedalus.zsh"

  # No zap stanza required

end
