# This file was generated by GoReleaser. DO NOT EDIT.
cask "dedalus" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "4074e23ce09594db068e3041526106558003de3d9186eb8730c5046e3a7e4e9d"
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "2eedfab0d80b877f344f1d50ae0e0d91edf166891a182d6fc2dbf3ff5e9a5e9e"
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "82ba5e68674fd25eb3f8fcee5bf386234f4259fc053adf161ed5fda9999359f4"
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ba5f8a931abb42dbe78cd21d4da644655bc421a8ec471f7ed7746453c1324dc"
      url "https://github.com/dedalus-labs/dedalus-cli/releases/download/v#{version}/dedalus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dedalus"
  desc "The official CLI for Dedalus."
  homepage "https://docs.dedaluslabs.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dedalus"
  manpage "man/man1/dedalus.1.gz"
  bash_completion "completions/dedalus.bash"
  fish_completion "completions/dedalus.fish"
  zsh_completion "completions/dedalus.zsh"

  # No zap stanza required

end
